# Generated by Django 5.2.5 on 2025-10-08 06:09

import church_app.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcements/', validators=[church_app.validators.validate_file_extension, church_app.validators.valdate_file_size])),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('size', models.PositiveIntegerField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BaptismRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('is_baptised', models.BooleanField(default=False)),
                ('is_study', models.BooleanField(default=False)),
                ('additional_information', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BenevolenceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_full_name', models.CharField(max_length=200)),
                ('head_phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('membership_status', models.CharField(choices=[('visitor', 'Visitor'), ('church_member', 'Church Member'), ('sabbath_school_member', 'Sabbath School Member')], max_length=200)),
                ('spouse_name', models.CharField(blank=True, max_length=200)),
                ('church_name', models.CharField(blank=True, max_length=200)),
                ('additional', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('membership_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DedicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_full_name', models.CharField(max_length=200)),
                ('date_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20)),
                ('father_full_name', models.CharField(max_length=200)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_phone_number', models.IntegerField()),
                ('mother_full_name', models.CharField(max_length=200)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('mother_phone_number', models.IntegerField()),
                ('additional_information', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time', models.TimeField()),
                ('department', models.CharField(choices=[('Sabbath School', 'Sabbath School'), ('AYS', 'Youth Ministries'), ('CM', 'Children’s Ministries'), ('FL', 'Family Life'), ('AWM', 'Adventist Women’s Ministries'), ('AMM', 'Adventist Men’s Ministries'), ('HM', 'Health Ministries'), ('ED', 'Education'), ('STW', 'Stewardship'), ('PARL', 'Public Affairs & Religious Liberty'), ('PUB', 'Publishing'), ('COM', 'Communication'), ('PCM', 'Public Campus Ministries'), ('ADV', 'Adventurers'), ('MUS', 'Music'), ('DEA', 'Deacons')], max_length=200)),
                ('image', models.ImageField(upload_to='events/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTransferForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('physical_address', models.CharField(blank=True, max_length=100)),
                ('from_church_name', models.CharField(max_length=200)),
                ('from_district_name', models.CharField(max_length=200)),
                ('from_conference_name', models.CharField(max_length=200)),
                ('from_address', models.CharField(max_length=200)),
                ('to_church_name', models.CharField(max_length=200)),
                ('to_district_name', models.CharField(max_length=200)),
                ('to_conference_name', models.CharField(max_length=200)),
                ('to_address', models.CharField(max_length=200)),
                ('additional_notes', models.TextField(blank=True)),
                ('board_minute_number', models.IntegerField()),
                ('first_reading_date', models.DateField()),
                ('second_reading_date', models.DateField()),
                ('business_number', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'completed'), ('Failed', 'failed')], default='pending', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('prayer_type', models.CharField(choices=[('personal request', 'personal request'), ('family request', 'family request'), ('health & healing', 'health & healing'), ('guidance & direction', 'guidance & direction'), ('thanksgiving', 'thanksgiving'), ('other', 'other')], default='personal request', max_length=200)),
                ('prayer_request', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('relationship', models.CharField(max_length=100)),
                ('benevolence_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='church_app.benevolenceform')),
            ],
        ),
    ]
