# Generated by Django 5.2.5 on 2025-09-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptismrequestform',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baptismrequestform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='prayerrequestform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='prayerrequestform',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prayerrequestform',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
