# Generated by Django 5.2.5 on 2025-10-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('membership_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='membershiptransferform',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='membershiptransferform',
            name='physical_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
