# Generated by Django 5.2.5 on 2025-10-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0002_prayerrequestform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptismrequestform',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], default='unread', max_length=150),
        ),
        migrations.AddField(
            model_name='contactform',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('unread', 'Unread')], default='unread', max_length=150),
        ),
        migrations.AddField(
            model_name='dedicationform',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread'), ('completed', 'Completed')], default='unread', max_length=150),
        ),
        migrations.AlterField(
            model_name='membershiptransferform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'completed'), ('failed', 'Failed')], default='pending', max_length=150),
        ),
    ]
