# Generated by Django 5.2.5 on 2025-10-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0002_churchmembers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptransferform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'completed'), ('Failed', 'failed')], default='pending', max_length=150),
        ),
    ]
