# Generated by Django 5.2.5 on 2025-09-23 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Faith', 'Faith'), ('Prayer', 'Prayer'), ('Doctrine', 'Doctrine'), ('Spiritual Growth', 'Spiritual Growth'), ('Stewardship', 'Stewardship'), ('Community', 'Community'), ('Prophecy', 'Prophecy')], max_length=200)),
                ('content', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.author')),
            ],
        ),
    ]
